# Generated by Django 5.2.9 on 2025-12-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
    ]
