# Generated by Django 5.2.9 on 2025-12-24 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app.course'),
        ),
    ]
